name: "React Build Action"
description: "Install, build, and test a React app"

inputs:
  node_version:
    description: "Node.js version"
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build React app
      run: npm run build
      shell: bash

    - name: Run tests
      run: npm test -- --watchAll=false
      shell: bash

