name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Step 2: Use your composite action
      - name: Run React Build Composite Action
        uses: ./.github/actions/react-build


