name: React CI with Composite Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Composite Action
        uses: ./.github/actions/react-build
        with:
          node_version: "20"
          working_directory: "."
          install_command: "npm install"
          build_command: "npm run build"
          test_command: "npm test"

