name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 

      - name: Run React Composite Action
        uses: ./.github/actions/react-build
        with:
          node_version: "20"

